function reportserver(){var O='bootstrap',P='begin',Q='gwt.codesvr.reportserver=',R='gwt.codesvr=',S='reportserver',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='javascript:""',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',$=' top: -1000px;',_='CSS1Compat',ab='<!doctype html>',bb='',cb='<html><head><\/head><body><\/body><\/html>',db='undefined',eb='DOMContentLoaded',fb=50,gb='Chrome',hb='eval("',ib='");',jb='script',kb='javascript',lb='moduleStartup',mb='moduleRequested',nb='Failed to load ',ob='head',pb='meta',qb='name',rb='reportserver::',sb='::',tb='gwt:property',ub='content',vb='=',wb='gwt:onPropertyErrorFn',xb='Bad handler "',yb='" for "gwt:onPropertyErrorFn"',zb='gwt:onLoadErrorFn',Ab='" for "gwt:onLoadErrorFn"',Bb='#',Cb='?',Db='/',Eb='img',Fb='clear.cache.gif',Gb='baseUrl',Hb='reportserver.nocache.js',Ib='base',Jb='//',Kb='gxt.user.agent',Lb='chrome',Mb='opera',Nb='trident',Ob='msie',Pb=11,Qb='ie11',Rb=10,Sb='ie10',Tb=9,Ub='ie9',Vb=8,Wb='ie8',Xb='msie 7',Yb='ie7',Zb='msie 6',$b='ie6',_b='safari',ac='version/3',bc='safari3',cc='version/4',dc='safari4',ec='safari5',fc='gecko',gc='rv:1.8',hc='gecko1_8',ic='gecko1_9',jc='adobeair',kc='air',lc=2,mc=3,nc=4,oc=5,pc=6,qc=7,rc='user.agent',sc='webkit',tc='user.agent.os',uc='macintosh',vc='mac os x',wc='mac',xc='linux',yc='windows',zc='win32',Ac='unknown',Bc='selectingPermutation',Cc='reportserver.devmode.js',Dc='0DF7ED50374E4B0D3CC676E2B7D4AD58',Ec=':1',Fc=':2',Gc=':3',Hc='40E0C4937C42A1726F8CF1026F2F78FD',Ic=':10',Jc=':11',Kc=':4',Lc=':5',Mc=':6',Nc=':7',Oc=':8',Pc=':9',Qc='4128C281AA55B5D5AEC0EE930D47D447',Rc='6100CE14ED63B596D65D452ECEAFFB79',Sc='6C8FF752EF43C098F0A55077F937557B',Tc='77A5A64C475E7A62DD35A50A1CADC3FD',Uc='9BF581CBEC85971E6E4A425987653940',Vc='C51A1AA1DEC8CAB6BFCA7582687DD41C',Wc='CEF196398C6DB7769B5D0559FA9DEB9C',Xc='CF5F53C4CEF02C73E62A470FC468887B',Yc='D380E8BBA7E64E690DB2E4228B0D9017',Zc='EE342D30826F19931826704E35D27169',$c=':',_c='.cache.js',ad='link',bd='rel',cd='stylesheet',dd='href',ed='loadExternalRefs',fd='reset.css',gd='end',hd='http:',jd='file:',kd='_gwt_dummy_',ld='__gwtDevModeHook:reportserver',md='Ignoring non-whitelisted Dev Mode URL: ',nd=':moduleBase';var o=window;var p=document;r(O,P);function q(){var a=o.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:S,sessionId:o.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
reportserver.__sendStats=r;reportserver.__moduleName=S;reportserver.__errFn=null;reportserver.__moduleBase=U;reportserver.__softPermutationId=V;reportserver.__computePropValue=null;reportserver.__getPropMap=null;reportserver.__installRunAsyncCode=function(){};reportserver.__gwtStartLoadingFragment=function(){return null};reportserver.__gwt_isKnownPropertyValue=function(){return false};reportserver.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[S]={moduleName:S};reportserver.__moduleStartupDone=function(e){var f=t[S].bindings;t[S].bindings=function(){var a=f?f():{};var b=e[reportserver.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(X);a.src=Y;a.id=S;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);u=a.contentDocument;if(!u){u=a.contentWindow.document}u.open();var b=document.compatMode==_?ab:bb;u.write(b+cb);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},fb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(hb));for(var i=V;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(W,j.length-W)))}h.appendChild(e.createTextNode(ib));g=e.createElement(jb);g.language=kb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=V;i<c.length;i++){g=e.createElement(jb);g.language=kb;g.text=c[i];f.appendChild(g);d(f,g)}}}
reportserver.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;if(reportserver.__errFn){n.onerror=function(){reportserver.__errFn(S,new Error(nb+code))}}p.getElementsByTagName(ob)[V].appendChild(n)}
reportserver.__startLoadingFragment=function(a){return D(a)};reportserver.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(jb);d.language=kb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(pb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(qb),k;if(j){j=j.replace(rb,bb);if(j.indexOf(sb)>=V){continue}if(j==tb){k=i.getAttribute(ub);if(k){var l,m=k.indexOf(vb);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=bb}c[j]=l}}else if(j==wb){k=i.getAttribute(ub);if(k){try{d=eval(k)}catch(a){alert(xb+k+yb)}}}else if(j==zb){k=i.getAttribute(ub);if(k){try{e=eval(k)}catch(a){alert(xb+k+Ab)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;reportserver.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Bb);if(b==-1){b=a.length}var c=a.indexOf(Cb);if(c==-1){c=a.length}var d=a.lastIndexOf(Db,Math.min(c,b));return d>=V?a.substring(V,d+W):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Eb);b.src=a+Fb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Gb);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(jb);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Hb)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Ib);if(a.length>V){return a[a.length-W].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Jb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return reportserver.__moduleBase+a}
function F(){var f=[];var g=V;function h(a,b){var c=f;for(var d=V,e=a.length-W;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
j[Kb]=function(){var a=navigator.userAgent.toLowerCase();if(a.indexOf(Lb)!=-1)return Lb;if(a.indexOf(Mb)!=-1)return Mb;if(a.indexOf(Nb)!=-1||a.indexOf(Ob)!=-1){if(p.documentMode>=Pb)return Qb;if(p.documentMode>=Rb)return Sb;if(p.documentMode>=Tb)return Ub;if(p.documentMode>=Vb)return Wb;if(a.indexOf(Xb)!=-1)return Yb;if(a.indexOf(Zb)!=-1)return $b;return Sb}if(a.indexOf(_b)!=-1){if(a.indexOf(ac)!=-1)return bc;if(a.indexOf(cc)!=-1)return dc;return ec}if(a.indexOf(fc)!=-1){if(a.indexOf(gc)!=-1)return hc;return ic}if(a.indexOf(jc)!=-1)return kc;return null};i[Kb]={air:V,chrome:W,gecko1_8:lc,gecko1_9:mc,ie10:nc,ie11:oc,ie8:pc,ie9:qc,safari3:Vb,safari4:Tb,safari5:Rb};j[rc]=function(){var a=navigator.userAgent.toLowerCase();var b=p.documentMode;if(function(){return a.indexOf(sc)!=-1}())return _b;if(function(){return a.indexOf(Ob)!=-1&&(b>=Rb&&b<Pb)}())return Sb;if(function(){return a.indexOf(Ob)!=-1&&(b>=Tb&&b<Pb)}())return Ub;if(function(){return a.indexOf(Ob)!=-1&&(b>=Vb&&b<Pb)}())return Wb;if(function(){return a.indexOf(fc)!=-1||b>=Pb}())return hc;return bb};i[rc]={gecko1_8:V,ie10:W,ie8:lc,ie9:mc,safari:nc};j[tc]=function(){var a=o.navigator.userAgent.toLowerCase();if(a.indexOf(uc)!=-1||a.indexOf(vc)!=-1){return wc}if(a.indexOf(xc)!=-1){return xc}if(a.indexOf(yc)!=-1||a.indexOf(zc)!=-1){return yc}return Ac};i[tc]={linux:V,mac:W,unknown:lc,windows:mc};__gwt_isKnownPropertyValue=function(a,b){return b in i[a]};reportserver.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};reportserver.__computePropValue=k;o.__gwt_activeModules[S].bindings=reportserver.__getPropMap;r(O,Bc);if(q()){return D(Cc)}var l;try{h([Sb,Sb,xc],Dc);h([Sb,Sb,wc],Dc+Ec);h([Sb,Sb,Ac],Dc+Fc);h([Sb,Sb,yc],Dc+Gc);h([kc,_b,xc],Hc);h([kc,_b,wc],Hc+Ec);h([ec,_b,Ac],Hc+Ic);h([ec,_b,yc],Hc+Jc);h([kc,_b,Ac],Hc+Fc);h([kc,_b,yc],Hc+Gc);h([Lb,_b,xc],Hc+Kc);h([Lb,_b,wc],Hc+Lc);h([Lb,_b,Ac],Hc+Mc);h([Lb,_b,yc],Hc+Nc);h([ec,_b,xc],Hc+Oc);h([ec,_b,wc],Hc+Pc);h([hc,hc,xc],Qc);h([hc,hc,wc],Qc+Ec);h([hc,hc,Ac],Qc+Fc);h([hc,hc,yc],Qc+Gc);h([Ub,Ub,xc],Rc);h([Ub,Ub,wc],Rc+Ec);h([Ub,Ub,Ac],Rc+Fc);h([Ub,Ub,yc],Rc+Gc);h([Qb,_b,xc],Sc);h([Qb,_b,wc],Sc+Ec);h([Qb,_b,Ac],Sc+Fc);h([Qb,_b,yc],Sc+Gc);h([Qb,Sb,xc],Tc);h([Qb,Sb,wc],Tc+Ec);h([Qb,Sb,Ac],Tc+Fc);h([Qb,Sb,yc],Tc+Gc);h([Qb,Wb,xc],Uc);h([Qb,Wb,wc],Uc+Ec);h([Qb,Wb,Ac],Uc+Fc);h([Qb,Wb,yc],Uc+Gc);h([Qb,hc,xc],Vc);h([Qb,hc,wc],Vc+Ec);h([Qb,hc,Ac],Vc+Fc);h([Qb,hc,yc],Vc+Gc);h([Wb,Wb,xc],Wc);h([Wb,Wb,wc],Wc+Ec);h([Wb,Wb,Ac],Wc+Fc);h([Wb,Wb,yc],Wc+Gc);h([bc,_b,xc],Xc);h([bc,_b,wc],Xc+Ec);h([bc,_b,Ac],Xc+Fc);h([bc,_b,yc],Xc+Gc);h([dc,_b,xc],Xc+Kc);h([dc,_b,wc],Xc+Lc);h([dc,_b,Ac],Xc+Mc);h([dc,_b,yc],Xc+Nc);h([Qb,Ub,xc],Yc);h([Qb,Ub,wc],Yc+Ec);h([Qb,Ub,Ac],Yc+Fc);h([Qb,Ub,yc],Yc+Gc);h([ic,hc,xc],Zc);h([ic,hc,wc],Zc+Ec);h([ic,hc,Ac],Zc+Fc);h([ic,hc,yc],Zc+Gc);l=f[k(Kb)][k(rc)][k(tc)];var m=l.indexOf($c);if(m!=-1){g=parseInt(l.substring(m+W),Rb);l=l.substring(V,m)}}catch(a){}reportserver.__softPermutationId=g;return D(l+_c)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement(ad);b.setAttribute(bd,cd);b.setAttribute(dd,D(a));p.getElementsByTagName(ob)[V].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(ed,P);c(fd);c(fd);r(ed,gd)}
B();reportserver.__moduleBase=C();t[S].moduleBase=reportserver.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==hd||o.location.protocol==jd);o.__gwt_activeModules[S].canRedirect=I;function J(){var b=kd;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(I&&J()){var K=ld;var L=o.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(md+L)}L=bb}if(L&&!o[K]){o[K]=true;o[K+nd]=C();var M=p.createElement(jb);M.src=L;var N=p.getElementsByTagName(ob)[V];N.insertBefore(M,N.firstElementChild||N.children[V]);return false}}}G();r(O,gd);A(H);return true}
reportserver.succeeded=reportserver();